# Generated by Django 5.0.6 on 2024-05-11 10:15

from django.db import migrations


# python manage.py makemigrations todo_app --empty

def load_initial_data(apps, schema_editor):
    task_model = apps.get_model('todo_app', 'Task')
    task_model.objects.create(
        title="Buy a new server",
        description="VPS OVH for my new website",
        closed=True
    )
    task_model.objects.create(
        title="Make backups",
        description="Need new SSD"
    )


class Migration(migrations.Migration):
    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
